name: test-arm64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  go-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - run: go build . 
      - run: echo 42 | ./fx .
